"""update carnet self reflexive relationship

Revision ID: aa315c66112f
Revises: 
Create Date: 2020-11-21 18:12:49.625969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa315c66112f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carnet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('id_parent_carnet', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_parent_carnet'], ['carnet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carnet_name'), 'carnet', ['name'], unique=False)
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_carnet', sa.Integer(), nullable=True),
    sa.Column('text_content', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['id_carnet'], ['carnet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_text_content'), 'answer', ['text_content'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1024), nullable=True),
    sa.Column('id_answer', sa.Integer(), nullable=True),
    sa.Column('need_paper', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_answer'], ['answer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_content'), 'question', ['content'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_content'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_answer_text_content'), table_name='answer')
    op.drop_table('answer')
    op.drop_index(op.f('ix_carnet_name'), table_name='carnet')
    op.drop_table('carnet')
    # ### end Alembic commands ###
